### ISSUE TITLE
Error - yarn prepare-demo

### ISSUE THREAD

**Issue by vinit21** [Felx-B/vscode-web#19]
yarn prepare-demo is throwing follow year. Also find the screenshot. Am I doing anything wrong ? 
Error: ENOENT: no such file or directory, stat './dist/extensions'
    at Object.statSync (node:fs:1588:3)
    at Object.statSync (C:\a\vsvsvsv\node_modules\graceful-fs\polyfills.js:307:34)
    at statSync (C:\a\vsvsvsv\node_modules\fs-extra\lib\util\stat.js:10:52)
    at getStatsSync (C:\a\vsvsvsv\node_modules\fs-extra\lib\util\stat.js:24:19)
    at Object.checkPathsSync (C:\a\vsvsvsv\node_modules\fs-extra\lib\util\stat.js:49:33)
    at Object.copySync (C:\a\vsvsvsv\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at Object.<anonymous> (C:\a\vsvsvsv\prepare-demo.js:9:5)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: './dist/extensions'

![image](https://user-images.githubusercontent.com/57453237/200646472-baa19ef6-8f0b-4a66-9e6e-ebe7b1ecd344.png)

**Comment by Felx-B** [comment]
Hi
You need to compile VSCode first
`yarn build`
It will create a `dist` folder, containing vscode web compiled like this:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/18530681/200852009-cfe8ca68-63fe-4959-8cb4-e0488104efad.png">
