### ISSUE TITLE
yarn build err

### ISSUE THREAD

**Issue by cws999** [Felx-B/vscode-web#9]
cd ./sample
yarn   ok
yarn sample   ok
http://127.0.0.1:8080   ok
cd ..
yarn   ok
yarn build   err
###########################
this is log
yarn run v1.22.18
$ node build.js
$ node --max_old_space_size=8192 ./node_modules/gulp/bin/gulp.js vscode-web-min
Error: Cannot find module 'vscode-gulp-watch'
Require stack:
- /home/cws/vscode-web-1.67.1/vscode/build/lib/watch/index.js
- /home/cws/vscode-web-1.67.1/vscode/build/lib/compilation.js
- /home/cws/vscode-web-1.67.1/vscode/build/gulpfile.js
- /home/cws/vscode-web-1.67.1/vscode/gulpfile.js
- /home/cws/vscode-web-1.67.1/vscode/node_modules/gulp-cli/lib/shared/require-or-import.js
- /home/cws/vscode-web-1.67.1/vscode/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /home/cws/vscode-web-1.67.1/vscode/node_modules/gulp-cli/index.js
- /home/cws/vscode-web-1.67.1/vscode/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/cws/vscode-web-1.67.1/vscode/build/lib/watch/index.js:6:73)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/cws/vscode-web-1.67.1/vscode/build/lib/watch/index.js',
    '/home/cws/vscode-web-1.67.1/vscode/build/lib/compilation.js',
    '/home/cws/vscode-web-1.67.1/vscode/build/gulpfile.js',
    '/home/cws/vscode-web-1.67.1/vscode/gulpfile.js',
    '/home/cws/vscode-web-1.67.1/vscode/node_modules/gulp-cli/lib/shared/require-or-import.js',
    '/home/cws/vscode-web-1.67.1/vscode/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/home/cws/vscode-web-1.67.1/vscode/node_modules/gulp-cli/index.js',
    '/home/cws/vscode-web-1.67.1/vscode/node_modules/gulp/bin/gulp.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
child_process.js:866
    throw err;
    ^

Error: Command failed: yarn gulp vscode-web-min
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at Object.<anonymous> (/home/cws/vscode-web-1.67.1/build.js:25:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 23578,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Felx-B** [comment]
Hi,
It seems to be a common issue of yarn not executing postinstall scripts
https://github.com/yarnpkg/yarn/issues/5476

I had this issue on a codespace environment, but not on my computer.
And it seems not happening on Github actions

You can manually trigger the post install script by executing
```sh
cd vscode
node build/npm/postinstall.js
```

**Comment by cws999** [comment]
Sorry, it might just be a problem with my computer
The directory ./sample provides a good example
I prefer to use "Felx-B/vscode-web/sample" over the bulky [VSCODE](https://code.visualstudio.com/)
